<a href="https://colab.research.google.com/github/chrishg23-jpg/HES-benchmark/blob/main/Neutrino015.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# -------------------------------
# Mass Model: HES-inspired
# -------------------------------
def hes_mass_model(delta, kappa):
    base = 1.0
    small_split = delta * 0.01
    large_split = kappa * 0.30
    m1 = base
    m2 = base + small_split
    m3 = base + small_split + large_split
    return np.array([m1, m2, m3])

# -------------------------------
# Sweep Result: Best-fit parameters
# -------------------------------
delta = 0.713756
kappa = 0.713756
sim_masses = hes_mass_model(delta, kappa)

# -------------------------------
# Spectral Confirmation
# -------------------------------
m1, m2, m3 = sim_masses
delta_m2_21 = m2**2 - m1**2
delta_m2_32 = m3**2 - m2**2
ratio = delta_m2_32 / delta_m2_21

# -------------------------------
# Calibration to Physical Units
# -------------------------------
scale_factor = 0.01  # Adjust based on HES calibration
physical_masses = sim_masses * scale_factor

# -------------------------------
# Mixing Matrix Emergence
# -------------------------------
def toy_mixing_matrix(masses):
    norm = np.linalg.norm(masses)
    v1 = masses / norm
    v2 = np.roll(v1, 1)
    v3 = np.roll(v1, 2)
    return np.vstack([v1, v2, v3])

def mixing_angles(U):
    s12 = abs(U[0,1])
    s23 = abs(U[1,2])
    s13 = abs(U[0,2])
    theta12 = np.arcsin(s12) * 180 / np.pi
    theta23 = np.arcsin(s23) * 180 / np.pi
    theta13 = np.arcsin(s13) * 180 / np.pi
    return theta12, theta23, theta13

U = toy_mixing_matrix(sim_masses)
theta12, theta23, theta13 = mixing_angles(U)

# -------------------------------
# Display Codex Summary
# -------------------------------
print("📜 Act XXXII: Codex & Calibration")
print(f"  Parameters: δ = {delta:.6f}, κ = {kappa:.6f}")
print(f"  Masses (sim units): {np.round(sim_masses, 6)}")
print(f"  Δm²_21 = {delta_m2_21:.6e}, Δm²_32 = {delta_m2_32:.6e}, Ratio = {ratio:.2f}")
print(f"  Masses (eV): {np.round(physical_masses, 6)}")
print("  Mixing Matrix:")
print(np.round(U, 4))
print(f"  Mixing Angles (degrees): θ12 ≈ {theta12:.2f}, θ23 ≈ {theta23:.2f}, θ13 ≈ {theta13:.2f}")


📜 Act XXXII: Codex & Calibration
  Parameters: δ = 0.713756, κ = 0.713756
  Masses (sim units): [1.       1.007138 1.221264]
  Δm²_21 = 1.432606e-02, Δm²_32 = 4.771606e-01, Ratio = 33.31
  Masses (eV): [0.01     0.010071 0.012213]
  Mixing Matrix:
[[0.5341 0.5379 0.6523]
 [0.6523 0.5341 0.5379]
 [0.5379 0.6523 0.5341]]
  Mixing Angles (degrees): θ12 ≈ 32.54, θ23 ≈ 32.54, θ13 ≈ 40.71
