<a href="https://colab.research.google.com/github/chrishg23-jpg/HES-benchmark/blob/main/Neutrino008.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 🔬 Hierarchical Sweep – Neutrino Mass Ratio Matching
import numpy as np

# -------------------------------
# Core Analysis Functions
# -------------------------------
def extract_mass_matrix(A_flavors):
    masses = np.sort(np.array(A_flavors))
    return masses**2

def compute_mass_differences(mass_squared):
    return mass_squared[1] - mass_squared[0], mass_squared[2] - mass_squared[1]

def compute_mixing_angles(A_flavors):
    norms = [a / np.linalg.norm(a) for a in A_flavors]
    overlaps = np.zeros((3, 3))
    for i in range(3):
        for j in range(3):
            overlaps[i, j] = np.abs(np.dot(norms[i], norms[j]))
    return overlaps

def calibrate_mass_units(sim_mass_values, reference_scale_eV):
    sim_spread = np.max(sim_mass_values) - np.min(sim_mass_values)
    scale_factor = reference_scale_eV / sim_spread
    return np.array(sim_mass_values) * scale_factor

# -------------------------------
# Sweep Parameters
# -------------------------------
delta_k_values = [0.01, 0.05, 0.10, 0.15, 0.20]
simulation_results = {}

# -------------------------------
# Hierarchical Mass Model
# -------------------------------
def simulate_hierarchical_masses(delta_k):
    base = 1.00
    small_split = 0.01 * delta_k / 0.20
    large_split = 0.30 * delta_k / 0.20
    return [base, base + small_split, base + small_split + large_split]

def simulate_flavor_vectors():
    return [np.random.rand(100) for _ in range(3)]

# -------------------------------
# Run Sweep
# -------------------------------
print("🚀 Running Hierarchical Sweep Across δ/κ...\n")

for dk in delta_k_values:
    print(f"🔹 δ/κ = {dk:.2f}")

    A_flavors = simulate_hierarchical_masses(dk)
    flavor_vectors = simulate_flavor_vectors()

    mass_squared = extract_mass_matrix(A_flavors)
    delta_m2_21, delta_m2_32 = compute_mass_differences(mass_squared)
    mixing_matrix = compute_mixing_angles(flavor_vectors)
    calibrated_masses = calibrate_mass_units(A_flavors, reference_scale_eV=0.05)

    simulation_results[dk] = (delta_m2_21, delta_m2_32)

    print(f"  Mass Estimates: {np.round(A_flavors, 6)}")
    print(f"  Mass²: {np.round(mass_squared, 6)}")
    print(f"  Δm²_21 = {delta_m2_21:.6f}, Δm²_32 = {delta_m2_32:.6f}")
    print(f"  Ratio Δm²_32 / Δm²_21 = {delta_m2_32 / delta_m2_21:.2f}")
    print(f"  Calibrated Masses (eV/c²): {np.round(calibrated_masses, 6)}")
    print(f"  Mixing Matrix:\n{np.round(mixing_matrix, 4)}\n")

print("✅ Sweep complete. Searching for physical match...\n")

# -------------------------------
# Match to Real Neutrino Hierarchy
# -------------------------------
def find_physical_match():
    target_solar = 7.5e-5      # eV²
    target_atmospheric = 2.5e-3 # eV²
    real_ratio = target_atmospheric / target_solar  # ≈ 33.3

    for dk in delta_k_values:
        sim_d21, sim_d32 = simulation_results[dk]
        ratio = sim_d32 / sim_d21
        if abs(ratio - real_ratio) < 5:
            print(f"🚨 PHYSICAL MATCH FOUND at δ/κ = {dk:.2f}")
            print(f"   Simulated ratio = {ratio:.2f}, Real ratio ≈ {real_ratio:.2f}")
            print(f"   Δm²_21 = {sim_d21:.6f}, Δm²_32 = {sim_d32:.6f}\n")

find_physical_match()


🚀 Running Hierarchical Sweep Across δ/κ...

🔹 δ/κ = 0.01
  Mass Estimates: [1.     1.0005 1.0155]
  Mass²: [1.      1.001   1.03124]
  Δm²_21 = 0.001000, Δm²_32 = 0.030240
  Ratio Δm²_32 / Δm²_21 = 30.23
  Calibrated Masses (eV/c²): [3.225806 3.227419 3.275806]
  Mixing Matrix:
[[1.     0.779  0.7137]
 [0.779  1.     0.7397]
 [0.7137 0.7397 1.    ]]

🔹 δ/κ = 0.05
  Mass Estimates: [1.     1.0025 1.0775]
  Mass²: [1.       1.005006 1.161006]
  Δm²_21 = 0.005006, Δm²_32 = 0.156000
  Ratio Δm²_32 / Δm²_21 = 31.16
  Calibrated Masses (eV/c²): [0.645161 0.646774 0.695161]
  Mixing Matrix:
[[1.     0.7557 0.7465]
 [0.7557 1.     0.7252]
 [0.7465 0.7252 1.    ]]

🔹 δ/κ = 0.10
  Mass Estimates: [1.    1.005 1.155]
  Mass²: [1.       1.010025 1.334025]
  Δm²_21 = 0.010025, Δm²_32 = 0.324000
  Ratio Δm²_32 / Δm²_21 = 32.32
  Calibrated Masses (eV/c²): [0.322581 0.324194 0.372581]
  Mixing Matrix:
[[1.     0.721  0.7027]
 [0.721  1.     0.7396]
 [0.7027 0.7396 1.    ]]

🔹 δ/κ = 0.15
  Mass Estima