<a href="https://colab.research.google.com/github/chrishg23-jpg/HES-benchmark/blob/main/Neutrino014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# -------------------------------
# Step 1: HES mass model
# -------------------------------
def hes_mass_model(delta, kappa):
    base = 1.0
    small_split = delta * 0.01
    large_split = kappa * 0.30
    m1 = base
    m2 = base + small_split
    m3 = base + small_split + large_split
    return np.array([m1, m2, m3])

# -------------------------------
# Step 2: Toy mixing matrix from mass ratios
# -------------------------------
def toy_mixing_matrix(masses):
    """
    Construct a toy mixing matrix based on normalized mass ratios.
    This is a placeholder — replace with entanglement-derived overlaps if available.
    """
    m1, m2, m3 = masses
    norm = np.linalg.norm(masses)
    v1 = np.array([m1, m2, m3]) / norm
    v2 = np.roll(v1, 1)
    v3 = np.roll(v1, 2)
    U = np.vstack([v1, v2, v3])
    return U

# -------------------------------
# Step 3: Extract mixing angles
# -------------------------------
def mixing_angles(U):
    """
    Extract approximate mixing angles from the toy matrix.
    Angles are derived from absolute values of matrix elements.
    """
    s12 = abs(U[0,1])
    s23 = abs(U[1,2])
    s13 = abs(U[0,2])
    theta12 = np.arcsin(s12) * 180 / np.pi
    theta23 = np.arcsin(s23) * 180 / np.pi
    theta13 = np.arcsin(s13) * 180 / np.pi
    return theta12, theta23, theta13

# -------------------------------
# Step 4: Run at best-fit parameters
# -------------------------------
delta = 0.713756
kappa = 0.713756
masses = hes_mass_model(delta, kappa)
U = toy_mixing_matrix(masses)
theta12, theta23, theta13 = mixing_angles(U)

# -------------------------------
# Step 5: Display results
# -------------------------------
print("🧪 Act XXXI: Mixing Matrix Emergence")
print(f"  Parameters: δ = {delta:.6f}, κ = {kappa:.6f}")
print(f"  Masses: {np.round(masses, 6)}")
print("  Toy Mixing Matrix (normalized):")
print(np.round(U, 4))
print(f"  Mixing Angles (degrees):")
print(f"    θ12 ≈ {theta12:.2f}, θ23 ≈ {theta23:.2f}, θ13 ≈ {theta13:.2f}")


🧪 Act XXXI: Mixing Matrix Emergence
  Parameters: δ = 0.713756, κ = 0.713756
  Masses: [1.       1.007138 1.221264]
  Toy Mixing Matrix (normalized):
[[0.5341 0.5379 0.6523]
 [0.6523 0.5341 0.5379]
 [0.5379 0.6523 0.5341]]
  Mixing Angles (degrees):
    θ12 ≈ 32.54, θ23 ≈ 32.54, θ13 ≈ 40.71
