<a href="https://colab.research.google.com/github/chrishg23-jpg/HES-benchmark/blob/main/Neutrino006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 🔬 Level 4 Sweep – Flavor Emergence Across δ/κ
import numpy as np

# -------------------------------
# Core Analysis Functions
# -------------------------------
def extract_mass_matrix(A_flavors):
    masses = np.sort(np.array(A_flavors))
    return masses**2

def compute_mass_differences(mass_squared):
    return mass_squared[1] - mass_squared[0], mass_squared[2] - mass_squared[1]

def compute_mixing_angles(A_flavors):
    norms = [a / np.linalg.norm(a) for a in A_flavors]
    overlaps = np.zeros((3, 3))
    for i in range(3):
        for j in range(3):
            overlaps[i, j] = np.abs(np.dot(norms[i], norms[j]))
    return overlaps

def calibrate_mass_units(sim_mass_values, reference_scale_eV):
    sim_spread = np.max(sim_mass_values) - np.min(sim_mass_values)
    scale_factor = reference_scale_eV / sim_spread
    return np.array(sim_mass_values) * scale_factor

# -------------------------------
# Sweep Parameters
# -------------------------------
delta_k_values = [0.01, 0.05, 0.10, 0.15, 0.20]

# -------------------------------
# Simulation Function (Replace with real data if available)
# -------------------------------
def simulate_flavor_amplitudes(delta_k):
    # Example: simulate 3 mass values with ~12% spread
    base = 1.00
    spread = 0.12 * delta_k / 0.20  # scale spread with delta_k
    return [base, base + spread/2, base + spread]

def simulate_flavor_vectors():
    return [np.random.rand(100) for _ in range(3)]

# -------------------------------
# Run Sweep
# -------------------------------
print("🚀 Running Level 4 Sweep Across δ/κ...\n")

for dk in delta_k_values:
    print(f"🔹 δ/κ = {dk:.2f}")

    A_flavors = simulate_flavor_amplitudes(dk)
    flavor_vectors = simulate_flavor_vectors()

    mass_squared = extract_mass_matrix(A_flavors)
    delta_m2_21, delta_m2_32 = compute_mass_differences(mass_squared)
    mixing_matrix = compute_mixing_angles(flavor_vectors)
    calibrated_masses = calibrate_mass_units(A_flavors, reference_scale_eV=0.05)

    print(f"  Mass Estimates: {np.round(A_flavors, 6)}")
    print(f"  Mass²: {np.round(mass_squared, 6)}")
    print(f"  Δm²_21 = {delta_m2_21:.6f}, Δm²_32 = {delta_m2_32:.6f}")
    print(f"  Calibrated Masses (eV/c²): {np.round(calibrated_masses, 6)}")
    print(f"  Mixing Matrix:\n{np.round(mixing_matrix, 4)}\n")

print("✅ Sweep complete. Codex inscription recommended.")


🚀 Running Level 4 Sweep Across δ/κ...

🔹 δ/κ = 0.01
  Mass Estimates: [1.    1.003 1.006]
  Mass²: [1.       1.006009 1.012036]
  Δm²_21 = 0.006009, Δm²_32 = 0.006027
  Calibrated Masses (eV/c²): [8.333333 8.358333 8.383333]
  Mixing Matrix:
[[1.     0.7627 0.782 ]
 [0.7627 1.     0.7527]
 [0.782  0.7527 1.    ]]

🔹 δ/κ = 0.05
  Mass Estimates: [1.    1.015 1.03 ]
  Mass²: [1.       1.030225 1.0609  ]
  Δm²_21 = 0.030225, Δm²_32 = 0.030675
  Calibrated Masses (eV/c²): [1.666667 1.691667 1.716667]
  Mixing Matrix:
[[1.     0.7529 0.7594]
 [0.7529 1.     0.764 ]
 [0.7594 0.764  1.    ]]

🔹 δ/κ = 0.10
  Mass Estimates: [1.   1.03 1.06]
  Mass²: [1.     1.0609 1.1236]
  Δm²_21 = 0.060900, Δm²_32 = 0.062700
  Calibrated Masses (eV/c²): [0.833333 0.858333 0.883333]
  Mixing Matrix:
[[1.     0.773  0.7548]
 [0.773  1.     0.7814]
 [0.7548 0.7814 1.    ]]

🔹 δ/κ = 0.15
  Mass Estimates: [1.    1.045 1.09 ]
  Mass²: [1.       1.092025 1.1881  ]
  Δm²_21 = 0.092025, Δm²_32 = 0.096075
  Calibrate